[package]
name = "apecrunch"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cursive = { version = "0.18.0", features = [ "toml" ] }
simple-error = "0.2.3"
fraction = "0.11.0"